// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmpbjcccezjfljyiwko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubXBiamNjY2V6amZsanlpd2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTkyMDUsImV4cCI6MjA2NTA5NTIwNX0.p7g6YR4r2V2i7SdBpfd33yN7Qftals86lgPvZu2JG7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function for sign up with custom redirect
export const signUpWithCustomRedirect = async (email: string, password: string, redirectUrl?: string) => {
  const finalRedirectUrl = redirectUrl || `${window.location.origin}/verify-email`;
  
  return await supabase.auth.signUp({
    email,
    password,
    options: {
      emailRedirectTo: finalRedirectUrl
    }
  });
};